FROM node:20.10-bookworm-slim

RUN apt update && apt install -y pandoc texlive-xetex

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm ci

COPY . .

ARG NEXT_BASE_PATH

EXPOSE 3000

CMD ["npm", "run", "dev"]
