FROM node:20.19-bullseye-slim

RUN apt update && apt install vim cron git -y

RUN apt update && \
    apt install -y python3 python3-venv python3-dev build-essential ghostscript && \
    apt clean && rm -rf /var/lib/apt/lists/*

RUN python3 -m venv /opt/venv

RUN /opt/venv/bin/pip install --upgrade pip && \
    /opt/venv/bin/pip install camelot-py[cv] pandas cryptography numpy

ENV PATH="/opt/venv/bin:$PATH"

RUN ln -s /opt/venv/bin/python /usr/local/bin/python3

RUN useradd -m clitools

RUN passwd -d clitools

RUN mkdir -p /etc/cron.d/ && touch /etc/cron.d/cron.allow && echo "root\nclitools" > /etc/cron.d/cron.allow

USER clitools

WORKDIR /home/clitools

# util to convert between versions
RUN git clone -b 12to13 https://github.com/stjiris/version-converter && cd version-converter && npm install && npm run build

# update jurisprudencia
RUN git clone https://github.com/stjiris/jurisprudencia-privada-etl && cd jurisprudencia-privada-etl && npm install && npm run build
#   https://crontab.guru/
#   At minute 0 past every 3rd hour from 9 through 18 on every day-of-week from Monday through Friday.
RUN (crontab -l; echo "0 9-18/3 * * 1-5 cd /home/clitools/jurisprudencia-privada-etl && /usr/local/bin/npm run run_dgsi >> ../jurisprudencia-dgsi-etl.stdout.log 2>> ../jurisprudencia-dgsi-etl.stderr.log") | crontab -
#   At 04:30 on Saturday.
RUN (crontab -l; echo "30 4 * * 6 cd /home/clitools/jurisprudencia-privada-etl && /usr/local/bin/npm run run_dgsi --full  >> ../jurisprudencia-dgsi-etl.full.stdout.log 2>> ../jurisprudencia-dgsi-etl.full.stderr.log") | crontab -

#   Every 10 min during week days update sharepoint
RUN (crontab -l; echo "*/10 9-18 * * 1-5 cd /home/clitools/jurisprudencia-privada-etl && /usr/local/bin/npm run run_sharepoint >> ../jurisprudencia-sharepoint-etl.stdout.log 2>> ../jurisprudencia-sharepoint-etl.stderr.log") | crontab -

# no build needed here
RUN git clone https://github.com/stjiris/backup-jurisprudencia && cd backup-jurisprudencia && npm install
#   At 10:00 on Sunday.
RUN (crontab -l; echo "0 10 * * 0 cd /home/clitools/backup-jurisprudencia && /usr/local/bin/node cli backup jurisprudencia.13.0,users.0.0,keys-info.0.0 >> ../backup-jurisprudencia.full.stdout.log 2>> ../backup-jurisprudencia.full.stderr.log") | crontab -

# update rss feed
RUN git clone https://github.com/stjiris/jurisprudencia-rss.git && cd jurisprudencia-rss && npm install && npm run build
# At minute 45 past every 3rd hour from 9 through 18 on every day-of-week from Monday through Friday.
RUN (crontab -l; echo "45 9-18/3 * * 1-5 cd /home/clitools/jurisprudencia-rss && /usr/local/bin/node dist >> ../jurisprudencia-rss.stdout.log 2>> ../jurisprudencia-rss.stderr.log") | crontab -

COPY entrypoint.sh .

USER root

RUN apt update && apt install -y locales apt-utils vim cron git && sed -i '/en_US.UTF-8/s/^# //' /etc/locale.gen && locale-gen en_US.UTF-8 && update-locale LANG=en_US.UTF-8

ENV LANG=en_US.UTF-8
ENV LANGUAGE=en_US:en
ENV LC_ALL=en_US.UTF-8

ENTRYPOINT ["./entrypoint.sh"]